services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - prom_data:/prometheus
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources
  sample-service:
    build:
      context: .
      dockerfile: integration-test.Dockerfile
    container_name: sample-service
    hostname: sample-service
    ports:
      - "8090:8090"
      - "8091:8091"
    volumes:
      - ./:/go/src/prometheus-grafana
volumes:
  prom_data:
